version: '3.8'

services:
  juliaos-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: juliaos:latest
    container_name: juliaos-server
    ports:
      - "8052:8052"
    volumes:
      - julia-data:/app/data
      - .env:/app/.env:ro
    command: ["julia", "--project=/app/julia", "/app/julia/server/julia_server.jl"]
    # Add a check to verify file exists
    entrypoint: ["/bin/bash", "-c", "if [ ! -f /app/julia/server/julia_server.jl ]; then echo 'Error: julia_server.jl not found'; ls -la /app/julia/server; exit 1; fi && exec julia --project=/app/julia /app/julia/server/julia_server.jl"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8052/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  juliaos-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: juliaos:latest
    container_name: juliaos-cli
    depends_on:
      juliaos-server:
        condition: service_healthy
    volumes:
      - julia-data:/app/data
      - .env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - JULIA_SERVER_URL=http://juliaos-server:8052
      - JULIA_SERVER_HOST=juliaos-server
      - JULIA_SERVER_PORT=8052
    stdin_open: true
    tty: true
    command: ["node", "/app/packages/cli/src/interactive.cjs"]
    # Add a check to verify file exists
    entrypoint: ["/bin/bash", "-c", "if [ ! -f /app/packages/cli/src/interactive.cjs ]; then echo 'Error: interactive.cjs not found'; ls -la /app/packages/cli/src; exit 1; fi && exec node /app/packages/cli/src/interactive.cjs"]

volumes:
  julia-data:
