# Precompilation directives for JuliaOS
# This file is automatically generated

# Precompile core modules
precompile(Tuple{typeof(Base.include), Module, String})
precompile(Tuple{typeof(JSON.parse), String})
precompile(Tuple{typeof(JSON.json), Dict{String, Any}})

# Precompile HTTP server functions
precompile(Tuple{typeof(HTTP.listen), String, Int})
precompile(Tuple{typeof(HTTP.Response), Int, Dict{String, String}, String})

# Precompile command handler functions
precompile(Tuple{typeof(JuliaOS.CommandHandler.handle_command), String, Dict{String, Any}})
